### ISSUE TITLE
Cocoapods support

### ISSUE THREAD

**Issue by robertherdzik** [IvanVorobei/TwitterLaunchAnimation#1]
Hi, could you add Cocoapods support? 🎉

**Comment by IvanVorobei** [comment]
Code is simple. You sure this is necessary?

**Comment by robertherdzik** [comment]
I think that Cocoapods support is needed even if code is simple. E.G. if someone use in project cocoapods for managing dependency he do not want to manually add some external frameworks anymore.

**Comment by IvanVorobei** [comment]
Ok, thanks. I will add in the near future

**Comment by X901** [comment]
Also if there is future update, User don't need to download it manually again , so Cocoapods support is good idea

**Comment by robertherdzik** [comment]
@X901 exactly 🎉

**Comment by IvanVorobei** [comment]
I added pod support
Use:

`pod 'Sparrow/LaunchAnimation’, :git => 'https://github.com/IvanVorobei/Sparrow.git’`
