### ISSUE TITLE
Laggy Animation

### ISSUE THREAD

**Issue by WillBishop** [IvanVorobei/TwitterLaunchAnimation#3]
Hello!

I like the library, but it has a weird lag glitch for me.

https://gyazo.com/404f2007e30aeb6ef6b8f21b7b695cb1 shows it, see the bottom of the "iphone" laggily appearing?

Any idea?

**Comment by IvanVorobei** [comment]
You user code draw or image?

**Comment by WillBishop** [comment]
Static image on launch screen

**Comment by IvanVorobei** [comment]
How much does the image that you are using weigh?

**Comment by WillBishop** [comment]
5KB Vector

**Comment by IvanVorobei** [comment]
Please, pack project and send me to hello@ivanvorobei.by
